version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: subscription-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - subscription-network

  app:
    build: .
    container_name: subscription-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - subscription-network

volumes:
  postgres_data:

networks:
  subscription-network:
    driver: bridge